export const USER_REQUIEST = 'USER_REQUIEST';
export const USER_SUCCCESS = 'USER_SUCCCESS';
export const USER_LOGOUT_SUCCCESS = 'USER_LOGOUT_SUCCCESS';

export const USER_FAIL = 'USER_FAIL';
export const USER_GETME_REQUIEST = 'USER_GETME_REQUIEST';
export const USER_GETME_SUCCCESS = 'USER_GETME_SUCCCESS';


export const USER_REGISTER_REQUIEST = "USER_REGISTER_REQUIEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "UREGISTER_SER_FAIL"

export const ACCOUNT_REQUIEST = "ACCOUNT_REQUIEST"
export const ACCOUNT_SUCCCESS = "ACCOUNT_SUCCCESS"
export const ACCOUNT_FAIL = "ACCOUNT_FAIL"

export const ACCOUNT_ADD_REQUIEST = "ACCOUNT_ADD_REQUIEST"
export const ACCOUNT_ADD_SUCCESS = "ACCOUNT_ADD_SUCCESS"
export const ACCOUNT_ADD_FAIL = "ACCOUNT_ADD_FAIL"

export const ACTIVITY_REQUIEST = "ACTIVITY_REQUIEST"
export const ACTIVITY_SUCCESS = "ACTIVITY_SUCCESS"
export const ACTIVITY_FAIL = "ACTIVITY_FAIL"

export const ALL_USER_REQUIEST = "ALL_USER_REQUIEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_FAIL = "ALL_USER_FAIL"

