export const USER_REQUIEST = 'USER_REQUIEST';
export const USER_SUCCCESS = 'USER_SUCCCESS';
export const USER_FAIL = 'USER_FAIL';

export const USER_REGISTER_REQUIEST = "USER_REGISTER_REQUIEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "UREGISTER_SER_FAIL"